export type EventMap<T extends EventTarget> =
	T extends HTMLMediaElement ? HTMLMediaElementEventMap :
	T extends HTMLElement ? HTMLElementEventMap :
	T extends SVGSVGElement ? SVGSVGElementEventMap :
	T extends SVGElement ? SVGElementEventMap :
	T extends Element ? ElementEventMap :
	T extends Document ? DocumentEventMap :
	T extends Window ? WindowEventMap :
	T extends AudioScheduledSourceNode ? AudioScheduledSourceNodeEventMap :
	T extends AudioWorkletNode ? AudioWorkletNodeEventMap :
	T extends OfflineAudioContext ? OfflineAudioContextEventMap :
	T extends IDBOpenDBRequest ? IDBOpenDBRequestEventMap :
	T extends RTCIceGatherer ? RTCIceGathererEventMap :
	T extends XMLHttpRequest ? XMLHttpRequestEventMap :
	T extends ServiceWorker ? ServiceWorkerEventMap :
	T extends Worker ? WorkerEventMap :
	T extends AbortSignal ? AbortSignalEventMap :
	T extends Animation ? AnimationEventMap :
	T extends BaseAudioContext ? BaseAudioContextEventMap :
	T extends BroadcastChannel ? BroadcastChannelEventMap :
	T extends EventSource ? EventSourceEventMap :
	T extends FileReader ? FileReaderEventMap :
	T extends IDBDatabase ? IDBDatabaseEventMap :
	T extends IDBRequest ? IDBRequestEventMap :
	T extends IDBTransaction ? IDBTransactionEventMap :
	T extends MediaDevices ? MediaDevicesEventMap :
	T extends MediaKeySession ? MediaKeySessionEventMap :
	T extends MediaQueryList ? MediaQueryListEventMap :
	T extends MediaSource ? MediaSourceEventMap :
	T extends MediaStream ? MediaStreamEventMap :
	T extends MediaStreamTrack ? MediaStreamTrackEventMap :
	T extends MessagePort ? MessagePortEventMap :
	T extends Notification ? NotificationEventMap :
	T extends PaymentRequest ? PaymentRequestEventMap :
	T extends Performance ? PerformanceEventMap :
	T extends PermissionStatus ? PermissionStatusEventMap :
	T extends RTCDTMFSender | RTCDtmfSender ? RTCDTMFSenderEventMap :
	T extends RTCDataChannel ? RTCDataChannelEventMap :
	T extends RTCDtlsTransport ? RTCDtlsTransportEventMap :
	T extends RTCIceTransport ? RTCIceTransportEventMap :
	T extends RTCPeerConnection ? RTCPeerConnectionEventMap :
	T extends RTCSctpTransport ? RTCSctpTransportEventMap :
	T extends RTCSrtpSdesTransport ? RTCSrtpSdesTransportEventMap :
	T extends ScreenOrientation ? ScreenOrientationEventMap :
	T extends ServiceWorkerContainer ? ServiceWorkerContainerEventMap :
	T extends ServiceWorkerRegistration ? ServiceWorkerRegistrationEventMap :
	T extends SourceBuffer ? SourceBufferEventMap :
	T extends SourceBufferList ? SourceBufferListEventMap :
	T extends SpeechRecognition ? SpeechRecognitionEventMap :
	T extends SpeechSynthesis ? SpeechSynthesisEventMap :
	T extends SpeechSynthesisUtterance ? SpeechSynthesisUtteranceEventMap :
	T extends TextTrackCue ? TextTrackCueEventMap :
	T extends TextTrack ? TextTrackEventMap :
	T extends TextTrackList ? TextTrackListEventMap :
	T extends VisualViewport ? VisualViewportEventMap :
	T extends WebSocket ? WebSocketEventMap :
	T extends XMLHttpRequestEventTarget ? XMLHttpRequestEventTargetEventMap :
	T extends AbstractWorker ? AbstractWorkerEventMap :
	T extends DocumentAndElementEventHandlers ? DocumentAndElementEventHandlersEventMap :
	T extends WindowEventHandlers ? WindowEventHandlersEventMap :
	T extends GlobalEventHandlers ? GlobalEventHandlersEventMap :
	never;
